Добавлена возможность публикации фронта
srclab/autodeploy pull request #12
Opened 2021-12-17 12:46 UTC by daurenalipbekov

2021-12-19 12:35 UTC, AlexNovicov requested changes

2021-12-19 12:35 UTC, AlexNovicov commented on src/AutoDeploy.php
> +                new Process(['cp', '-rf',  $this->config['front_build_dir'], $this->config['front_publish_dir']]),
Если я говорю, что нужно сделать как в ./run.sh, значит нужно сделать как в ./run.sh - https://i.imgur.com/18LBqrV.png. Почему нет пересоздания пустой директории для публикации нового билда?

2021-12-20 05:38 UTC, daurenalipbekov commented
@AlexNovicov поправил.

2021-12-20 06:32 UTC, AlexNovicov approved these changes

2021-12-20 06:32 UTC, merged

2021-12-20 06:32 UTC, AlexNovicov commented
Обнови пакет на клиенте и создай новый пул