Добавлена перезагрузка очередей
srclab/autodeploy pull request #7
Opened 2021-09-27 03:00 UTC by daurenalipbekov

https://app.asana.com/0/0/1200199516648773/f

2021-09-27 07:48 UTC, AlexNovicov requested changes

2021-09-27 07:48 UTC, AlexNovicov commented on src/AutoDeploy.php
> +            new Process(['php', 'artisan', 'queue:restart']),
Это на обычные очереди, у нас horizon

2021-09-27 08:35 UTC, daurenalipbekov commented
@AlexNovicov все поправил.

2021-09-30 13:12 UTC, AlexNovicov approved these changes

2021-09-30 13:12 UTC, merged