Создание пулл запроса в дев ветку при наличии метки тестирования
srclab/autodeploy pull request #8
Opened 2021-09-27 04:45 UTC by daurenalipbekov

https://app.asana.com/0/0/1200336033654420/f

2021-09-27 08:38 UTC, AlexNovicov requested changes

2021-09-27 08:38 UTC, AlexNovicov commented on src/AutoDeploy.php
> +    }
Этот метод не относится к этому классу. Нужно создать отдельный класс GitHub например и перенести туда этот метод.

Метод должен принимать конкретные данные (head, title, body, url),  а не объект

Тут еще нужно копировать метки с основного пула.

И сделай еще добавление ссылки вида "DEV developer...autodeploy-permissions" в конец описания основного пул запроса, после создания пул запроса в дев

2021-09-29 05:07 UTC, daurenalipbekov commented
@AlexNovicov все поправил.

2021-09-29 06:47 UTC, AlexNovicov requested changes

2021-09-29 06:47 UTC, AlexNovicov commented on src/AutoDeploy.php
> +            $this->github->add_labels_to_pull_request($new_pull->issue_url, $labels);
Вынеси все это в отдельный метод, чтобы все к куче не было

2021-09-29 06:47 UTC, AlexNovicov commented on src/AutoDeploy.php
> +        return $pull_branch_names_to_dev;
Нет проверки на пустоту $pulls_to_branch. Придет null и все ляжет.

Перенести этот метод в GitHub

2021-09-29 06:47 UTC, AlexNovicov commented on src/AutoDeploy.php
> +            && $github_payload_decode->action === 'labeled'
Ты проверял? Мне кажется до сюда не дойдет, т.к. это условие `if (!$this->isTargetBranchPullRequest($github_event, $github_payload_decode) && !$this->isTargetBranchPush($github_event, $github_payload_decode))` выкинет

2021-09-29 06:47 UTC, AlexNovicov commented on src/GitHub.php
> +    public function __construct()
Аннотация

2021-09-29 06:47 UTC, AlexNovicov commented on src/GitHub.php
> +    public function create_pull_request($url, $base, $head, $title, $body)
Названия методов должны быть в camelCase стиле. Исключения только контроллеры

2021-09-29 06:47 UTC, AlexNovicov commented on src/GitHub.php
> +     * @param string $body
Аннотация не полная

2021-09-29 06:47 UTC, AlexNovicov commented on src/GitHub.php
> +            ];
Можно проще и без дополнительной переменной: compact('base', ...

2021-09-29 06:47 UTC, AlexNovicov commented on src/GitHub.php
> +            }
Можно проще: array_filter(compact('title', ...))

2021-09-29 06:47 UTC, AlexNovicov commented on src/GitHub.php
> +            if (!empty($maintainer_can_modify)) {
!empty(null) = false
!empty(false) = false

Это условия будет истинно только при $maintainer_can_modify, что неверно. Нужно использовать !is_null

2021-09-30 02:37 UTC, daurenalipbekov commented
@AlexNovicov все поправил.

2021-09-30 10:37 UTC, AlexNovicov requested changes

2021-09-30 10:37 UTC, AlexNovicov commented on src/AutoDeploy.php
> +        && $github_payload->pull_request->base->ref !== $this->config['developer_branch'];
Добавь еще проверку, что целевая ветка master, чтобы не создавать пул в дев при мерже между другими ветками

2021-09-30 10:37 UTC, AlexNovicov commented on src/GitHub.php
> +                $request_body = compact('maintainer_can_modify', $request_body);
Это перезапишет $request_body и все что было ранее записано пропадет.

2021-09-30 12:58 UTC, daurenalipbekov commented
@AlexNovicov все поправил.

2021-09-30 13:01 UTC, AlexNovicov approved these changes

2021-09-30 13:01 UTC, merged